install-ng: handle correctly hostname, exit on error

diff --git a/src/install-ng b/src/install-ng
--- a/src/install-ng
+++ b/src/install-ng
@@ -69,6 +69,13 @@ if [ -z "$hostname" ]
 then
 	hostname=`hostname -f`
 fi
+if [ -z "${hostname}" ]
+then
+	echo "Missing hostname"
+	usage
+	exit 1
+fi
+	
 echo "Using hostname=$hostname"
 
 # Load some script
