Backport from trunk: Nicer look while waiting for the VM/LXC to come up

diff --git a/tests/scripts/start_vm b/tests/scripts/start_vm
--- a/tests/scripts/start_vm
+++ b/tests/scripts/start_vm
@@ -19,17 +19,21 @@ else
 fi
 
 # Loop until engine is up and ssh is running
-ssh -o 'StrictHostKeyChecking=no' "root@$HOST" uname -a
-ret=$?
-for loop in 1 2 3 4 5 6 7 8 9
-do
+test_host () {
+    ssh -o 'StrictHostKeyChecking=no' "root@$HOST" uname -a 2>/dev/null 
+}
 
-	if [ $ret -ne 0 ];then
-		echo -n $loop
-		sleep 20;
-		ssh -o 'StrictHostKeyChecking=no' "root@$HOST" uname -a
-		ret=$?
-	fi
+echo "Waiting for $HOST to come up..."
+i=0
+while [ $i -lt 10 ] && ! test_host ; do
+    sleep 10
+    i=$(($i+1))
+    echo -n .
 done
-sleep 1
-exit $ret
+
+if test_host ; then
+    echo " OK"
+else
+    echo " FAIL"
+    exit 1
+fi
